FROM ubuntu:24.04 AS builder

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    ninja-build \
    git \
    curl \
    zip \
    unzip \
    tar \
    pkg-config

WORKDIR /opt

RUN git clone https://github.com/microsoft/vcpkg.git

WORKDIR /opt/vcpkg

RUN ./bootstrap-vcpkg.sh

WORKDIR /pp

COPY . .

RUN cmake -S gameserver \
    -B gameserver/build \
    -DCMAKE_BUILD_TYPE=Release \
    _DCMAKE_TOOLCHAIN_FILE=/opt/vcpkg/scripts/buildsystems/vcpkg.cmake

RUN cmake --build gameserver/build -j

FROM ubuntu:24.04 AS runtime

RUN apt-get update && apt-get install -y \
    libstdc++6

WORKDIR /app

COPY --from=builder /app/gameserver/build/gameserver ./gameserver

EXPOSE 27015/udp

ENTRYPOINT [ "./gameserver" ]