FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build

WORKDIR /src

COPY backend ./backend

WORKDIR /src/backend

RUN dotnet restore MOBA.slnx

RUN dotnet publish AuthService/AuthService.csproj\
    -c Release \
    -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime

WORKDIR /app

COPY --from=build /app/publish .

EXPOSE 8080

ENTRYPOINT [ "dotnet", "AuthService.dll" ]